apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wcf
spec:
  template:
    metadata:
      labels:
        component: wcf
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows    
      containers:
      - name: wcf
        image: smarthotel360/registrationwcf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: DefaultConnection
            valueFrom:
              configMapKeyRef:
                name: wcf-cm
                key: dbconnection
