apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smarthotel-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:   
  rules:
  - host: smhotel360win.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
      - path: /svc
        backend:
          serviceName: api
          servicePort: 80