apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sql
spec:
  template:
    metadata:
      labels:
        component: sql
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows      
      containers:
      - name: sql
        image: microsoft/mssql-server-windows-express:2017-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1433
          name: sql-port
        env:
          - name: ACCEPT_EULA
            valueFrom:
              configMapKeyRef:
                name: sql
                key: eula
          - name: sa_password
            valueFrom:
              configMapKeyRef:
                name: sql
                key: sapwd