apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sql
spec:
  template:
    metadata:
      labels:
        component: sql
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows      
      containers:
      - name: sql
        image: microsoft/mssql-server-windows-express:2017-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1433