apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  template:
    metadata:
      labels:
        component: api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows    
      containers:
      - name: api
        image: smarthotels/sh360reg-api:aks
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-port
        env:
          - name: DefaultConnection
            valueFrom:
              configMapKeyRef:
                name: api
                key: dbconnection
          - name: UseStoreKPIsStatefulService
            valueFrom:
              configMapKeyRef:
                name: api
                key: kpistatefulservice