apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  template:
    metadata:
      labels:
        component: web
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows      
      containers:
      - name: web
        image: smarthotels/sh360reg-web:aks
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: UseStoreKPIsStatefulService
            valueFrom:
              configMapKeyRef:
                name: web-cm
                key: kpiactive
          - name: WcfServiceUri
            valueFrom:
              configMapKeyRef:
                name: web-cm
                key: apiurl
           