apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  template:
    metadata:
      labels:
        component: web
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows      
      containers:
      - name: web
        image: smarthotel360registration-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: WcfServiceUri
            valueFrom:
              configMapKeyRef:
                name: web-cm
                key: wcfurl
           