version: '3.4'

services:

  web:
    image: ${REGISTRY:-smarthotels}/sh360reg-web:aks
    env_file:
     - .env
    ports:
      - "5000:80"
    build:
      context: ./SmartHotel.Registration.Web
      dockerfile: Dockerfile    
      args:
        tag: ${wintag:-4.8-windowsservercore-ltsc2019}
    depends_on:
      - api
  api:
    image: ${REGISTRY:-smarthotels}/sh360reg-api:aks
    env_file:
     - .env
    ports:
      - "4001:80"
    build:
      context: ./SmartHotel.Registration.Wcf
      dockerfile: Dockerfile    
      args:
        tag: ${wintag:-4.8-windowsservercore-ltsc2019}
    depends_on:
      - sql
  sql:
    image: microsoft/mssql-server-windows-express:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - sa_password=P@ssw0rd!
