version: '3.4'

services:

  web:
    image: smarthotel360registration-web:latest
    env_file:
     - .env
    ports:
      - "9000:80"
    build:
      context: ./SmartHotel360.Registration.Web
      dockerfile: Dockerfile    
      args:
        tag: ${wintag:-4.8-windowsservercore-ltsc2019}
    depends_on:
      - wcf
  wcf:
    image: smarthotel360registration-wcf:latest
    env_file:
     - .env
    ports:
      - "9001:80"
    build:
      context: ./SmartHotel360.Registration.WCF
      dockerfile: Dockerfile    
      args:
        tag: ${wintag:-4.8-windowsservercore-ltsc2019}
    depends_on:
      - sql
  sql:
    image: microsoft/mssql-server-windows-express:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - sa_password=Azure2019!
